spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

jwt:
  secret: SuperMegaDuperCrazyMazyDazySecretWordLongEnoughIHope
  expiration: 3600000

server:
  port: 8080
